### ISSUE TITLE
build script changes

### ISSUE THREAD

**Issue by daytonpid** [firepick1/FireSight#30]
Hey, Karl

So as it turns out not all systems contain lsb_release and have Debian like tags. So I propose a new universal way of checking Raspberry Pi versions in the build script, we should add g++ checking as well. Also do we need jansson build docs? if not we should add -DJANSSON_BUILD_DOCS=OFF to build as well. There is currently zero support for recognizing armv7l when installing opencv binaries from the repo. I have tested the below code on all raspberry pi variants but the pi 3 and it works flawlessly,

 elif [ "$(cat /proc/cpuinfo | grep -ci -m1 'BCM2709')" == "1" ]; then
    echo "SYSTEM	: Raspberry Pi 2"
    echo "COMMAND	: sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
    sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip

  elif [ "$(free | awk '/^Mem:/{print $2}')" > "246000" ]; then
    echo "SYSTEM	: Raspberry Pi 1 (512MB)"
    echo "COMMAND	: sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
    sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip

  elif [ "$(free | awk '/^Mem:/{print $2}')" < "246000" ]; then
    echo "SYSTEM	: Raspberry Pi 1 (256MB)"
    echo "COMMAND	: sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
    sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip

EDIT: Sorry for re opening and closing, was a mistake on this damn android app

**Comment by firepick1** [comment]
Dayton, please repost to Slack for group discussion. Most excellent
observation!

On Mon, May 2, 2016 at 8:49 PM, Dayton Pidhirney <notifications@github.com>
wrote:

> Hey, Karl
>
> So as it turns out not all systems contain lsb_release and have Debian
> like tags. So I propose a new universal way of checking Raspberry Pi
> versions in the build script, we should add g++ checking as well. Also do
> we need jansson build docs? if not we should add -DJANSSON_BUILD_DOCS=OFF
> to build as well.
>
> elif [ "$(cat /proc/cpuinfo | grep -ci -m1 'BCM2709')" == "1" ]; then
> echo "SYSTEM : Raspberry Pi 2"
> echo "COMMAND : sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
> sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip
>
> elif [ "$(free | awk '/^Mem:/{print $2}')" > "246000" ]; then
> echo "SYSTEM : Raspberry Pi 1 (512MB)"
> echo "COMMAND : sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
> sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip
>
> elif [ "$(free | awk '/^Mem:/{print $2}')" < "246000" ]; then
> echo "SYSTEM : Raspberry Pi 1 (256MB)"
> echo "COMMAND : sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip"
> sudo -E unzip -d /usr/local rpi-opencv.2.4.8.zip
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firepick1/FireSight/issues/30>
>



-- 
Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by daytonpid** [comment]
Will close when 692ddae9a36324c376160cf23d61f264aabfa193 has been merged
