### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by seba-wetzel** [firepick1/FireSight#31]
Hello, I'm trying to compiling the sources and I had the folling error:

FireSight/FireSight.hpp:61:12: error: cannot declare field ‘firesight::HoleRecognizer::mser’ to be of abstract type ‘cv::MSER’
       MSER mser;
            ^

FireSight/bgSub.cpp: In member function ‘bool firesight::Pipeline::apply_backgroundSubtractor(json_t*, json_t*, firesight::Model&)’:
/opt/programacion/framework/FireSight/bgSub.cpp:59:84: error: invalid new-expression of abstract class type ‘cv::BackgroundSubtractorMOG2’
 ractor = new BackgroundSubtractorMOG2(history, varThreshold, bShadowDetection);
                                                                              ^
FireSight/bgSub.cpp:105:24: error: ‘class cv::BackgroundSubtractor’ has no member named ‘operator()’
  pSubtractor->operator()(bgImage, fgMask, learningRate);
                        ^
FireSight/bgSub.cpp:105:24: error: ‘class cv::BackgroundSubtractor’ has no member named ‘operator()’
  pSubtractor->operator()(bgImage, fgMask, learningRate);
                        ^

CMakeFiles/_firesight.dir/build.make:62: fallo en las instrucciones para el objetivo 'CMakeFiles/_firesight.dir/bgSub.cpp.o'
make[2]: *** [CMakeFiles/_firesight.dir/bgSub.cpp.o] Error 1
CMakeFiles/Makefile2:178: fallo en las instrucciones para el objetivo 'CMakeFiles/_firesight.dir/all'
make[1]: *** [CMakeFiles/_firesight.dir/all] Error 2
Makefile:149: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
ERROR	: make failed (RC=2)

I attach the entire output here: http://pastebin.com/TyzrxG6g
Thank you people, and sorry for my bad english!

**Comment by seba-wetzel** [comment]
I forget to say that I usin Ubuntu 16.04 (64 bits) with g++ (Ubuntu 5.3.1-14ubuntu2)

**Comment by firepick1** [comment]
Hmm. Sebastian, I just recompiled firesight myself on Ubuntu 14 64-bit with opencv 2.4.12
(Chromebook Pixel). It also compiles on Raspberry Pi Ubuntu.  Our power is out in the house, so it's hard for me to troubleshoot further. I'm hoping Dayton or Simon may be able to help.

The MSER warning implies it's having trouble with OpenCV, so it might be a version problem.

--Karl

**Comment by seba-wetzel** [comment]
When execute the ./build script, it run an opencv installation from the repositories:
libopencv-dev ya está en su versión más reciente (2.4.9.1+dfsg-1.5ubuntu1) (This mean "opencv it's already in the most recent version")
I can see that it's a different version of opencv than yours, i will try to make a downgrade of version.

**Comment by firepick1** [comment]
Sebastian, the auto-download of opencv is for Raspberry PI. Each version of Ubuntu seems to have a different version of OpenCV, so the only good way to get a reliable version is to build it yourself if the build fails.  It would be very helpful if you could download the sources for 2.4.12 so that we can compare. It will be easier for me to help you. Thanks!

**Comment by seba-wetzel** [comment]
I build opencv from source version 2.4.12, and all work perfectly. 
One idea I had is that  Maybe the script should build from source instead download from the repository, or just like it does in the raspberry pi, a pre-build version. 
Anyway, sorry for the trouble, and thank you very much!

**Comment by firepick1** [comment]
Sebastian, many thanks for looking into this. Looks like we have a direct dependency on 2.4.12 OpenCV. I will try to think up some way to deal with this. Probably build from source for non-Pi as you suggest.
